[build]
command = ""
publish = "."

# jika pakai 1 halaman (SPA sederhana)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# header keamanan dasar
[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "geolocation=(), camera=(), microphone=()"
