name: HTML Lint & Link Check
on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HTMLHint
        uses: Cyb3r-Jak3/htmlhint-action@v1
        with:
          files: "."
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --exclude-mail "./**/*.html"
